import { Service } from './types';

export const INITIAL_SERVICES: Service[] = [
  // TIKTOK
  {
    id: 101,
    name: 'TikTok Followers [Instant Start • 10K/Day • Non-Drop Cute 🌸]',
    category: 'TikTok Followers',
    platform: 'TikTok',
    rate: 1.45,
    originalRate: 1.10,
    min: 50,
    max: 500000,
    dripfeed: true,
    refill: true,
    refillDays: 30,
    avgTime: '12 minutes',
    speed: '10K/Day',
    quality: 'High Quality',
    description: 'High retention TikTok followers with profile pictures and bio. Guaranteed non-drop for 30 days. Link format: https://www.tiktok.com/@username',
    providerServiceId: 101,
  },
  {
    id: 102,
    name: 'TikTok Video Likes [Real Active • Viral Algorithm Booster 🚀]',
    category: 'TikTok Likes',
    platform: 'TikTok',
    rate: 0.85,
    originalRate: 0.60,
    min: 50,
    max: 100000,
    dripfeed: true,
    refill: true,
    refillDays: 30,
    avgTime: '5 minutes',
    speed: '25K/Day',
    quality: 'Real Active',
    description: 'Instant start likes from real active TikTok users. Helps trigger FYP recommendation algorithm. Link format: https://vm.tiktok.com/XYZ or https://www.tiktok.com/@user/video/12345678',
    providerServiceId: 102,
  },
  {
    id: 103,
    name: 'TikTok FYP Viral Views [Ultra Fast • 100K/Day • Real Watch Time ⚡]',
    category: 'TikTok Views',
    platform: 'TikTok',
    rate: 0.08,
    originalRate: 0.04,
    min: 100,
    max: 10000000,
    dripfeed: true,
    refill: false,
    avgTime: 'Instant (1-2 min)',
    speed: '100K/Day',
    quality: 'VIP Cute',
    description: 'High watch time video views. Perfect for entering the FYP. Instant delivery starts immediately.',
    providerServiceId: 103,
  },
  {
    id: 104,
    name: 'TikTok Custom Cute Comments [Positive / Emojis Only ✨]',
    category: 'TikTok Comments',
    platform: 'TikTok',
    rate: 4.20,
    originalRate: 3.20,
    min: 10,
    max: 5000,
    dripfeed: false,
    refill: true,
    avgTime: '20 minutes',
    speed: '500/Day',
    quality: 'VIP Cute',
    description: 'Custom relevant comments with cute emojis, hype phrases, and genuine engagement tone.',
    providerServiceId: 104,
  },

  // INSTAGRAM
  {
    id: 201,
    name: 'Instagram Followers [Real Profile • 365 Days Refill Button 💖]',
    category: 'Instagram Followers',
    platform: 'Instagram',
    rate: 1.80,
    originalRate: 1.35,
    min: 50,
    max: 200000,
    dripfeed: true,
    refill: true,
    refillDays: 365,
    avgTime: '15 minutes',
    speed: '15K/Day',
    quality: 'VIP Cute',
    description: 'Premium Instagram followers with posts, stories, and realistic bios. 365-day refill button enabled directly on dashboard. Profile must be public.',
    providerServiceId: 201,
  },
  {
    id: 202,
    name: 'Instagram Likes [Instant • High Retention • Explore Page Hit 🌟]',
    category: 'Instagram Likes',
    platform: 'Instagram',
    rate: 0.45,
    originalRate: 0.30,
    min: 20,
    max: 50000,
    dripfeed: true,
    refill: true,
    refillDays: 30,
    avgTime: '3 minutes',
    speed: '50K/Day',
    quality: 'High Quality',
    description: 'Real Instagram likes that improve reach on Explore Page and hashtags. Immediate start upon order placement.',
    providerServiceId: 202,
  },
  {
    id: 203,
    name: 'Instagram Reels Views [Viral Explosive • Real Impression + Reach 🎬]',
    category: 'Instagram Views',
    platform: 'Instagram',
    rate: 0.12,
    originalRate: 0.08,
    min: 100,
    max: 5000000,
    dripfeed: true,
    refill: false,
    avgTime: '5 minutes',
    speed: '200K/Day',
    quality: 'Real Active',
    description: 'Boosts your Reel impression, profile visits, and viral distribution on the Instagram algorithm.',
    providerServiceId: 203,
  },
  {
    id: 204,
    name: 'Instagram Story Views + Poll Votes [VIP Engaging Accounts 📊]',
    category: 'Instagram Engagement',
    platform: 'Instagram',
    rate: 0.95,
    originalRate: 0.70,
    min: 100,
    max: 100000,
    dripfeed: false,
    refill: false,
    avgTime: '10 minutes',
    speed: '30K/Day',
    quality: 'High Quality',
    description: 'Views on all current active stories with optional interactive sticker votes.',
    providerServiceId: 204,
  },

  // YOUTUBE
  {
    id: 301,
    name: 'YouTube Subscribers [Permanent Non-Drop • Organic Speed 🔴]',
    category: 'YouTube Subscribers',
    platform: 'YouTube',
    rate: 18.50,
    originalRate: 14.00,
    min: 50,
    max: 50000,
    dripfeed: true,
    refill: true,
    refillDays: 60,
    avgTime: '1 hour',
    speed: '1K/Day',
    quality: 'Real Active',
    description: 'Monetization-safe YouTube subscribers. High retention, slow organic speed to prevent YouTube channel audits. 60-day replacement refill.',
    providerServiceId: 301,
  },
  {
    id: 302,
    name: 'YouTube High Retention Views [Suggested & Search Traffic 📈]',
    category: 'YouTube Views',
    platform: 'YouTube',
    rate: 2.10,
    originalRate: 1.60,
    min: 500,
    max: 1000000,
    dripfeed: true,
    refill: true,
    refillDays: 30,
    avgTime: '30 minutes',
    speed: '10K/Day',
    quality: 'VIP Cute',
    description: 'Views with average watch time of 3-7+ minutes. Helps trigger YouTube recommendation sidebar.',
    providerServiceId: 302,
  },
  {
    id: 303,
    name: 'YouTube Shorts Views [Instant Blast • 50K/Day ⚡]',
    category: 'YouTube Views',
    platform: 'YouTube',
    rate: 0.75,
    originalRate: 0.50,
    min: 100,
    max: 2000000,
    dripfeed: true,
    refill: false,
    avgTime: 'Instant',
    speed: '50K/Day',
    quality: 'High Quality',
    description: 'Fast viral Shorts views with high swipe-through rate for the Shorts feed algorithm.',
    providerServiceId: 303,
  },

  // TWITTER / X
  {
    id: 401,
    name: 'X (Twitter) Followers [Active NFT & Web3/Crypto Handles 🐦]',
    category: 'Twitter Followers',
    platform: 'Twitter',
    rate: 6.90,
    originalRate: 5.20,
    min: 50,
    max: 100000,
    dripfeed: true,
    refill: true,
    refillDays: 30,
    avgTime: '25 minutes',
    speed: '5K/Day',
    quality: 'High Quality',
    description: 'Real profiles with banners, avatars, and tweet history. Safe for account standing.',
    providerServiceId: 401,
  },
  {
    id: 402,
    name: 'X (Twitter) Retweets & Likes Combo [Algorithm Hype 🔁]',
    category: 'Twitter Engagement',
    platform: 'Twitter',
    rate: 3.40,
    originalRate: 2.50,
    min: 25,
    max: 20000,
    dripfeed: false,
    refill: true,
    avgTime: '10 minutes',
    speed: '10K/Day',
    quality: 'VIP Cute',
    description: 'Combined delivery of RTs and likes for maximum social proof and trending impact.',
    providerServiceId: 402,
  },

  // SPOTIFY
  {
    id: 501,
    name: 'Spotify Plays [Royalty Eligible • USA / Global Top Chart 🎧]',
    category: 'Spotify Streams',
    platform: 'Spotify',
    rate: 1.20,
    originalRate: 0.90,
    min: 1000,
    max: 1000000,
    dripfeed: true,
    refill: true,
    refillDays: 30,
    avgTime: '45 minutes',
    speed: '20K/Day',
    quality: 'Real Active',
    description: 'Premium streams with 90s+ listening duration. Eligible for editorial playlist consideration and royalties.',
    providerServiceId: 501,
  },
  {
    id: 502,
    name: 'Spotify Artist Monthly Listeners [Safe Algorithm Reach 🎵]',
    category: 'Spotify Listeners',
    platform: 'Spotify',
    rate: 2.80,
    originalRate: 2.10,
    min: 500,
    max: 500000,
    dripfeed: true,
    refill: true,
    avgTime: '2 hours',
    speed: '5K/Day',
    quality: 'VIP Cute',
    description: 'Boosts your artist profile monthly listener metric directly on your artist page.',
    providerServiceId: 502,
  },

  // TELEGRAM
  {
    id: 601,
    name: 'Telegram Channel Members [Non-Drop • Real Cute Accounts ✈️]',
    category: 'Telegram Members',
    platform: 'Telegram',
    rate: 1.10,
    originalRate: 0.80,
    min: 50,
    max: 200000,
    dripfeed: true,
    refill: true,
    refillDays: 60,
    avgTime: '5 minutes',
    speed: '50K/Day',
    quality: 'High Quality',
    description: 'Stable channel subscribers with 60-day auto-refill guarantee.',
    providerServiceId: 601,
  },
  {
    id: 602,
    name: 'Telegram Post Views [Last 5 Posts Auto-View 👁️]',
    category: 'Telegram Views',
    platform: 'Telegram',
    rate: 0.05,
    originalRate: 0.03,
    min: 100,
    max: 1000000,
    dripfeed: false,
    refill: false,
    avgTime: 'Instant',
    speed: '100K/Day',
    quality: 'Standard',
    description: 'Instant views distributed across recent posts in your public channel.',
    providerServiceId: 602,
  },

  // THREADS
  {
    id: 701,
    name: 'Threads Followers [Meta Verified Mixed • Fast 🌀]',
    category: 'Threads Followers',
    platform: 'Threads',
    rate: 2.90,
    originalRate: 2.20,
    min: 50,
    max: 50000,
    dripfeed: true,
    refill: true,
    refillDays: 30,
    avgTime: '15 minutes',
    speed: '5K/Day',
    quality: 'VIP Cute',
    description: 'Grow your Meta Threads presence with high-quality follower profiles.',
    providerServiceId: 701,
  },

  // FACEBOOK
  {
    id: 801,
    name: 'Facebook Page Likes + Followers [Worldwide Quality 👥]',
    category: 'Facebook Page',
    platform: 'Facebook',
    rate: 3.20,
    originalRate: 2.40,
    min: 100,
    max: 50000,
    dripfeed: true,
    refill: true,
    refillDays: 30,
    avgTime: '30 minutes',
    speed: '5K/Day',
    quality: 'High Quality',
    description: 'High quality fan page likes + followers with organic distribution.',
    providerServiceId: 801,
  },

  // TWITCH
  {
    id: 901,
    name: 'Twitch Channel Followers [Instant Start • Streamer Boost 🎮]',
    category: 'Twitch Followers',
    platform: 'Twitch',
    rate: 1.95,
    originalRate: 1.40,
    min: 50,
    max: 50000,
    dripfeed: true,
    refill: true,
    avgTime: '10 minutes',
    speed: '10K/Day',
    quality: 'High Quality',
    description: 'Instant followers to unlock Twitch Affiliate status faster.',
    providerServiceId: 901,
  }
];

export const INITIAL_ORDERS = [
  {
    id: 84920,
    serviceId: 101,
    serviceName: 'TikTok Followers [Instant Start • 10K/Day • Non-Drop Cute 🌸]',
    platform: 'TikTok' as const,
    link: 'https://www.tiktok.com/@cutestars.official',
    quantity: 2500,
    charge: 3.63,
    startCount: 1420,
    remains: 320,
    status: 'In Progress' as const,
    createdAt: '2026-03-30 14:15',
    apiForwarded: true,
    apiOrderId: 'AP-948211'
  },
  {
    id: 84918,
    serviceId: 202,
    serviceName: 'Instagram Likes [Instant • High Retention • Explore Page Hit 🌟]',
    platform: 'Instagram' as const,
    link: 'https://www.instagram.com/p/Cz849Xy12A/',
    quantity: 1000,
    charge: 0.45,
    startCount: 450,
    remains: 0,
    status: 'Completed' as const,
    createdAt: '2026-03-30 11:20',
    apiForwarded: true,
    apiOrderId: 'AP-948190'
  },
  {
    id: 84905,
    serviceId: 103,
    serviceName: 'TikTok FYP Viral Views [Ultra Fast • 100K/Day • Real Watch Time ⚡]',
    platform: 'TikTok' as const,
    link: 'https://www.tiktok.com/@pastelgirl/video/7391823901',
    quantity: 10000,
    charge: 0.80,
    startCount: 215,
    remains: 0,
    status: 'Completed' as const,
    createdAt: '2026-03-29 18:40',
    apiForwarded: true,
    apiOrderId: 'AP-947932'
  },
  {
    id: 84882,
    serviceId: 301,
    serviceName: 'YouTube Subscribers [Permanent Non-Drop • Organic Speed 🔴]',
    platform: 'YouTube' as const,
    link: 'https://youtube.com/@viralcutelabs',
    quantity: 500,
    charge: 9.25,
    startCount: 680,
    remains: 180,
    status: 'Processing' as const,
    createdAt: '2026-03-29 09:12',
    apiForwarded: false
  }
];
